# Generated by Django 5.0.6 on 2024-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_email_student_postion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='postion',
            field=models.CharField(choices=[('Head', 'Head'), ('AH', 'AH'), ('SG', 'SG')], default='1', max_length=100),
        ),
    ]
