# Generated by Django 5.0.7 on 2024-07-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_postion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discription',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='instagram',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('PREVIOUS', 'PREVIOUS')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='postion',
            field=models.CharField(choices=[('Head', 'Head'), ('AH', 'AH'), ('SG', 'SG')], max_length=100),
        ),
    ]
