# Generated by Django 5.0.7 on 2024-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWCMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mem', models.CharField(blank=True, default='student', max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, default=2024, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('hometown', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True)),
            ],
        ),
    ]
