# Generated by Django 5.0.7 on 2024-10-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_swcmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
