# Generated by Django 5.0.7 on 2024-10-05 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('picture', models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, default=2024, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('picture', models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True)),
                ('pdf', models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True)),
                ('youtube', models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='SWCMembers',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtIZ5I4Qg-MO4Q6VYx8HgfqoNI-Ot4HRZVZTe8zQqkdZ-up5dE', null=True),
        ),
    ]
